server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 666666
mybatis:
  mapper-locations: classpath*:mapper/*.xml

# 跨域设置
cors:
  allowed-origins: /*
  allowed-headers: Content-Type,X-Adminid,X-Token
  allowed-methods: GET,POST,OPTIONS,PATCH

aliyun:
  oss:
    file:
      endpoint: oss-cn-shanghai.aliyuncs.com
      keyid: LTAIz7uiYCvAbELb
      keysecret: lnMTq7v6v76wsusteS0gvgmciBg7BB
      #bucket可以在控制台创建，也可以使用java代码创建
      bucketname: kongbenfitness
      basefile: headimg
