server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 666666
mybatis:
  mapper-locations: classpath*:mapper/*.xml

# 跨域设置
cors:
  allowed-origins: /*
  allowed-headers: Content-Type,X-Adminid,X-Token
  allowed-methods: GET,POST,OPTIONS,PATCH

