server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vue_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
    username: root
    password: 666666
      # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 666666
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 20
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接池中的最大空闲连接
        max-idle: 10
    # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000

mybatis:
  # 扫描mapper
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # 数据库 映射 驼峰
     map-underscore-to-camel-case: true

# 跨域设置
cors:
  allowed-origins: /*
  allowed-headers: Content-Type,X-Adminid,X-Token
  allowed-methods: GET,POST,OPTIONS,PATCH

logging:
  level:
    com:
      neo:
        mapper: debug

